# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190927_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='name',
        ),
        migrations.AddField(
            model_name='specialty',
            name='name',
            field=models.ManyToManyField(blank=True, null=True, related_name='userSpecialties', to='main.User'),
        ),
    ]
