# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190927_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='instructor',
            field=models.ManyToManyField(blank=True, null=True, related_name='mySpecialties', to='main.User'),
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='name',
        ),
        migrations.AddField(
            model_name='specialty',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
