# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-12 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191110_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timeExperience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
