# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191112_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numAppointment',
            field=models.IntegerField(default=0),
        ),
    ]
